add pid to tokio::net::unix::UCred
tokio-rs/tokio pull request #2633
Opened 2020-06-25 18:47 UTC by Kloenk

## Motivation
Fixed: #2632

## Solution
Provided pid as Option<libc::pid_t> so solaris and macos does not break.

2020-06-25 20:08 UTC, Darksonn commented
This is a breaking change:
```rust
use tokio::net::unix::UCred;

fn main() {
    let a = UCred {
        uid: 10,
        gid: 10,
    };
}
```

2020-06-25 20:28 UTC, Kloenk commented
> This is a breaking change:
> ```rust
> use tokio::net::unix::UCred;
> 
> fn main() {
>     let a = UCred {
>         uid: 10,
>         gid: 10,
>     };
> }
> ```

Should it be behind a feature flag? How should that be named?

2020-06-26 14:53 UTC, Darksonn commented
A feature flag does not solve the issue. If some code compiles without a certain feature flag, it should also compile with that feature flag enabled. This is because when compiling code using Tokio, every feature required by any dependency is enabled for every dependency, and adding one dependency should not break other dependencies.

This change will have to wait for v0.3 of Tokio.

2020-07-20 17:05 UTC, Darksonn commented
I will close the PR for now and come back to this once we prepare to release v0.3.

2020-10-04 13:18 UTC, Darksonn commented
We are working on v0.3 now. Can you submit a commit that merges in the master branch to your branch?

2020-10-10 22:00 UTC, Kloenk commented
> We are working on v0.3 now. Can you submit a commit that merges in the master branch to your branch?

rebased it onto master

2020-10-11 07:32 UTC, Darksonn commented
Hi. We made a change to this struct such that changes like this are not breaking changes in the future in #2936. Can you rebase again? Sorry about that.

2020-10-11 08:44 UTC, Darksonn commented
It's a bit awkward that we can't get it under MacOS. What would be missing to change that? Perhaps it's better to not provide the function on mac and not use an `Option`?

2020-10-11 08:52 UTC, Kloenk commented
> It's a bit awkward that we can't get it under MacOS. What would be missing to change that? Perhaps it's better to not provide the function on mac and not use an `Option`?

For me it's a mac. So I don't know enough aboutacos api, if it is possible

2020-10-11 09:49 UTC, Kloenk commented
Will disable it for now under MacOS.

I think since 4.2BSD MacOS also supports getsockopt. But I'm not sure, and don't have anything to test it on.

2020-10-16 16:07 UTC, Kloenk commented
As far as I can understand the docs and the source of darwin, it's not possible for us to get the PID of the peer process.
The `LOCAL_PEERCRED` option was added to macos, but it seems like [xucred](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/ucred.h#L132-L137) does not contain a PID.

2020-10-16 17:19 UTC, Kloenk commented
Found another option, will try to get something working for darwin

2020-10-16 18:40 UTC, Kloenk commented
It breaks, while saying bad address. But yet sure why

2020-10-16 20:32 UTC, Darksonn commented
Let me know if you figure out that its not possible on MacOS.

2020-10-17 10:44 UTC, Kloenk commented
Hot it to work on my local MacOS hackintosh.

2020-10-17 11:10 UTC, taiki-e commented
> not use an `Option`?

I don't think this is a good idea, as users must specify complex cfgs (`cfg(any(target_os * 2 or 4)`) for proper use. Also, even if this function becomes available on more platforms, it is not available to users unless they manually update cfgs.

2020-10-17 11:11 UTC, taiki-e requested changes
Please change the return type to `Option` or use `#[cfg_attr(docsrs, doc(cfg(any(target_os = ...))))]` on `pid` function to improve docs.

2020-10-17 11:20 UTC, Darksonn commented
I was hoping we could make it work everywhere and get rid of both the option and cfg.

2020-10-17 11:22 UTC, Kloenk commented
I didn't this LOCAL_PEEREPID on another bsd. So no luck there

2020-10-17 12:00 UTC, taiki-e commented
> I was hoping we could make it work everywhere and get rid of both the option and cfg.

That is most preferable if that is possible, but I don't think we need to block this PR until it becomes work everywhere. Also, if it becomes work everywhere in the future, we can add a document that says "This function always returns `Some` since tokio v1.x.y".

2020-10-17 12:35 UTC, Darksonn commented
Fair enough. We can return an `Option` and document on which OSes it works.

2020-10-17 15:48 UTC, Kloenk commented
So readding the Option<pid_t> I removed before?

2020-10-21 11:39 UTC, Darksonn commented
Yes.

2020-10-22 17:53 UTC, Kloenk commented
Added it, with a small comment saying, where it is implemented

2020-10-24 11:50 UTC, taiki-e approved these changes

2020-10-31 09:30 UTC, merged