sync: add `mpsc::Sender::closed` future
tokio-rs/tokio pull request #2840
Opened 2020-09-17 11:11 UTC by zaharidichev

## Motivation
Adding closed future, makes it possible to select over closed and some other work, so that the task is woken when the channel is closed and can proactively cancel itself.

## Solution
Added a mpsc::Sender::closed future that will become ready when the receiver is closed

2020-09-21 16:31 UTC, carllerche requested changes
Thanks! Left some comments.

2020-09-21 16:31 UTC, carllerche commented on tokio/src/sync/mpsc/chan.rs
> +        let aquired_lost_notification =
This logic should no longer be necessary w/ #2839. A poll should not be ready and is just to establish the waiter.

2020-09-22 08:32 UTC, zaharidichev commented
Thanks, I addressed the comments. The loom tests will be failing until #2839 is merged.

2020-09-24 10:29 UTC, zaharidichev commented
Not sure why CI fails, tests pass locally

2020-09-24 11:04 UTC, Darksonn commented
I restarted CI.

2020-09-25 15:39 UTC, carllerche approved these changes
Thanks :+1:

2020-09-25 15:40 UTC, merged