docs: More docs for UdpSocket
tokio-rs/tokio pull request #2883
Opened 2020-09-25 01:10 UTC by leshow

#Motivation

I always found the udp docs a little lackluster, after using them extensively for some time I thought it might be nice to flesh it out a bit. I asked in the tokio-docs discord and others seemed open to it, so here they are! Would love to hear your thoughts

## Solution

A few small code examples similar to the way the tcp section is set up, with an explanation of the different ways to use `UdpSocket`.

I had a full larger example with `split` but found that it's been removed for `UdpSocket` in master, I hope that's temporary, if not is there anything I can do to get similar functionality back? i.e. being able to `send_to`/`recv_from` concurrently

2020-09-25 02:28 UTC, leshow commented
Does anyone else have issues with `futures_util` when running cargo test locally? I'm running from the `tokio` sub crate in the workspace:

```
~/dev/rust/tokio/tokio master
❯ cargo test --features full
   Compiling autocfg v0.1.7
   Compiling syn v1.0.41
   Compiling rand_core v0.4.2
   Compiling getrandom v0.1.13
   Compiling ppv-lite86 v0.2.6
   Compiling pin-project-internal v0.4.23
   Compiling log v0.4.8
   Compiling proc-macro-nested v0.1.3
   Compiling once_cell v1.4.1
   Compiling futures-sink v0.3.5
   Compiling futures-io v0.3.5
   Compiling remove_dir_all v0.5.2
   Compiling bitflags v1.2.1
   Compiling pin-utils v0.1.0
   Compiling byteorder v1.3.2
   Compiling bit-vec v0.5.1
   Compiling quick-error v1.2.2
   Compiling regex-syntax v0.6.18
   Compiling futures-channel v0.3.5
   Compiling wait-timeout v0.2.0
   Compiling futures-task v0.3.5
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling bit-set v0.5.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_core v0.5.1
   Compiling mio v0.6.21
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling num-traits v0.2.10
   Compiling c2-chacha v0.2.3
   Compiling mio-uds v0.6.7
   Compiling rand_chacha v0.2.1
   Compiling rand v0.7.2
   Compiling tempfile v3.1.0
   Compiling rusty-fork v0.2.2
   Compiling proptest v0.9.4
   Compiling proc-macro-hack v0.5.11
   Compiling tokio-macros v0.3.0 (/home/leshow/dev/rust/tokio/tokio-macros)
   Compiling tokio v0.3.0 (/home/leshow/dev/rust/tokio/tokio)
   Compiling futures-macro v0.3.5
   Compiling pin-project v0.4.23
   Compiling futures-util v0.3.5
   Compiling tokio-test v0.3.0 (/home/leshow/dev/rust/tokio/tokio-test)
   Compiling futures-executor v0.3.5
   Compiling futures v0.3.1
error[E0433]: failed to resolve: could not find `document_join_macro` in `futures_util`
   --> /home/leshow/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.1/src/lib.rs:504:15
    |
504 | futures_util::document_join_macro! {
    |               ^^^^^^^^^^^^^^^^^^^ could not find `document_join_macro` in `futures_util`

error[E0433]: failed to resolve: could not find `document_select_macro` in `futures_util`
   --> /home/leshow/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.1/src/lib.rs:528:15
    |
528 | futures_util::document_select_macro! {
    |               ^^^^^^^^^^^^^^^^^^^^^ could not find `document_select_macro` in `futures_util`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `futures`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

2020-09-25 06:45 UTC, taiki-e commented
> Does anyone else have issues with `futures_util` when running cargo test locally? I'm running from the `tokio` sub crate in the workspace:

it could be fixed by run `cargo update`.

2020-09-25 13:32 UTC, leshow commented
Ah great, that did the trick. I realized that the api has been changed so `UdpSocket` is no longer `mut`. I suppose that's why `split` is gone?

I'd like to include another example of putting `UdpSocket` in an `Arc` and using it concurrently if that's alright. Since it was not obvious to me that it was even possible to do that, having been used to the `split` API before.

2020-10-05 16:47 UTC, carllerche approved these changes
thanks :+1:

2020-10-06 14:01 UTC, taiki-e requested changes

2020-10-06 14:01 UTC, taiki-e commented on tokio/src/net/udp/socket.rs
> +    ///  #  }
```suggestion
    /// use tokio::net::UdpSocket;
    /// # use std::{io, net::SocketAddr};
    ///
    /// # #[tokio::main]
    /// # async fn main() -> io::Result<()> {
    /// let sock = UdpSocket::bind("0.0.0.0:8080".parse::<SocketAddr>().unwrap()).await?;
    /// let mut buf = [0u8; 32];
    /// let (len, addr) = sock.recv_from(&mut buf).await?;
    /// println!("received {:?} bytes from {:?}", len, addr);
    /// # Ok(())
    /// # }
```

2020-10-06 14:54 UTC, taiki-e approved these changes

2020-10-07 01:12 UTC, merged