net: make UCred fields private
tokio-rs/tokio pull request #2936
Opened 2020-10-09 05:39 UTC by taiki-e

Refs: #2928

2020-10-09 07:18 UTC, Darksonn reviewed
The `uid_t` and `gid_t` types are just integers. I'd probably just go for methods that return them by-copy.

2020-10-09 17:05 UTC, carllerche requested changes
Thanks :+1: minor request. I would remove the &mut accesors for the time being until there is a request for them.

2020-10-09 17:05 UTC, carllerche commented on tokio/src/net/unix/ucred.rs
> +    pub fn uid_mut(&mut self) -> &mut uid_t {
I would leave off the mut accesors for now.

2020-10-09 17:05 UTC, carllerche commented on tokio/src/net/unix/ucred.rs
> +    pub fn gid_mut(&mut self) -> &mut gid_t {
Same, I would avoid the mut for now.

2020-10-09 17:34 UTC, taiki-e commented
> I would remove the &mut accesors for the time being until there is a request for them.

Make sense, I removed them.

2020-10-11 07:30 UTC, Darksonn approved these changes

2020-10-11 07:31 UTC, merged