Eliza/tcp keepalive
tokio-rs/tokio pull request #3146
Opened 2020-11-16 20:32 UTC by hawkw

Depends on #3145

## Motivation

Tokio v0.3 no longer exposes a way to configure TCP keepalive probes.
Many users need this functionality, so we want to re-expose keepalive
configuration via `TcpSocket`.

## Solution

This commit exposes the TCP keepalive configuration added to `mio`'s
`TcpSocket` in tokio-rs/mio#1385. This includes a method for enabling
keepalvie and checking if keepalive is enabled, a builder interface for
configuring keepalive parameters (keepalive time, the amount of time
before keepalive probes are sent, keepalive interval, the time between
each probe, and keepalive retries, the number of failed probes before a
connection is closed), and accessors for the values of keepalive
parameters. Due to Windows API limitations, `mio` has to provide a
builder for configuring keepalive parameters, since they must all be set
in one API call. Therefore, we re-export the keepalive builder struct.
If the `mio` API changes, we should be able to replace this with our own
type transparently, so it didn't seem necessary to wrap this --- if I'm
wrong, please let me know!

Fixes: #3082

2020-11-17 00:12 UTC, bdonlan commented on tokio/src/net/tcp/socket.rs
> +    /// specifications may be omitted.
Rounded down or up? What happens if this rounds to zero?

2020-11-17 00:12 UTC, bdonlan commented on tokio/src/net/tcp/socket.rs
> +    pub use mio::net::TcpKeepalive;
This makes a mio type part of the public API, which is probably not ideal.

2020-11-17 00:21 UTC, carllerche requested changes
I'm hesitant to add this API at this time. This goes beyond what Tokio has done to date with regard to socket options. Until now, we have added socket option APIs that are essentially pass-through to the OS call. This attempts to provide a portable API that abstracts differences.

I also see a potential issue with the implementation in Mio where a single call to `set_keepalive_params` may result in multiple sub calls. If the first sub call succeeds, but the second fails, the socket state is inconsistent. All other socket option setters are atomic.

Perhaps it is best to leave such configuration to other crates or the user to call themselves?

2020-11-17 00:21 UTC, carllerche commented on tokio/src/net/tcp/socket.rs
> +    pub use mio::net::TcpKeepalive;
We are not exposing mio as part of Tokio's public API. If we do this, we will need to re-define the type.

2020-11-17 00:21 UTC, carllerche commented on tokio/src/net/mod.rs
> +    pub use tcp::socket::{TcpSocket, TcpKeepalive};
We probably can keep this type in `tokio::net::tcp` and not re-export it.

2020-11-17 23:51 UTC, carllerche commented
Closing as we decided in Discord to punt this.

2020-11-17 23:51 UTC, closed without merging

2020-11-17 23:56 UTC, hawkw commented
@carllerche wdyt about exposing _just_ keepalive time (time to the initial probe)? That, at least, can be configured consistently across all platforms.

2020-11-18 04:50 UTC, carllerche commented
If it is consistent across platforms then it seems fine to me.