task: add missing feature flags for docs.rs
tokio-rs/tokio pull request #3236
Opened 2020-12-08 22:37 UTC by nylonicious

Fixes #3206 on `0.2.x` branch.

2020-12-09 22:47 UTC, Darksonn requested changes
I made a quick test to double-check this, but they actually also require the `rt-core` feature.

2020-12-09 22:47 UTC, Darksonn commented on tokio/src/task/task_local.rs
> +#[cfg_attr(docsrs, doc(cfg(feature = "rt-util")))]
```suggestion
#[cfg_attr(docsrs, doc(cfg(all(feature = "rt-util", "rt-core"))))]
```

2020-12-09 22:47 UTC, Darksonn commented on tokio/src/task/task_local.rs
> +#[cfg_attr(docsrs, doc(cfg(feature = "rt-util")))]
```suggestion
#[cfg_attr(docsrs, doc(cfg(all(feature = "rt-util", "rt-core"))))]
```

2020-12-09 23:03 UTC, nylonicious commented
Sorry, my bad I paid more attention to 0.3 version. Should be fine now I think.

2020-12-10 07:28 UTC, Darksonn approved these changes
Thanks!

2020-12-10 07:29 UTC, merged