Improve Sleep documentation for !Unpin
tokio-rs/tokio pull request #3330
Opened 2020-12-24 09:06 UTC by Darksonn

Currently the documentation for `Sleep` renders like this:

![scr](https://user-images.githubusercontent.com/928074/103076890-02a75680-45cf-11eb-9ce0-23e8f120774b.png)
![scr](https://user-images.githubusercontent.com/928074/103076905-0e931880-45cf-11eb-8c04-610a2e2c2541.png)

It is not exactly clear from this documentation that `Sleep` is `!Unpin`. This PR manually implements the `project` method on `Sleep` so that the documentation is improved to this:

![scr](https://user-images.githubusercontent.com/928074/103076981-35514f00-45cf-11eb-8f6a-547501c15e2c.png)
![scr](https://user-images.githubusercontent.com/928074/103077003-3e422080-45cf-11eb-8626-318aa868cd99.png)

I will let it be up to the rest of the team to decide if this is worth the extra unsafe block.

2020-12-24 09:57 UTC, taiki-e requested changes
I would recommend adding a document explaining that this future is `!Unpin`, instead of adding unsafe code.

2020-12-24 11:17 UTC, quasicomputational commented
+1 for documenting this and giving explicit instructions on how to pin `Sleep`. I just got as far as writing a bug report for the loss of a usable `Unpin` impl between 0.3.6 and 1.0.0, and only realised it was intentional when I was looking for the commit that 'broke' it and realised it was deliberate.

2020-12-29 04:20 UTC, jyn514 commented
@Darksonn would it help if rustdoc could tell that `__Origin: Unpin` is always false and stop showing the blanket impl if so?

2020-12-29 09:02 UTC, Darksonn commented
Yes, that would solve the problem.

2021-01-21 11:54 UTC, Darksonn commented
Closing in favor of #3457.

2021-01-21 11:54 UTC, closed without merging