Update CHANGELOG.md
tokio-rs/tokio pull request #3336
Opened 2020-12-25 06:39 UTC by arniu

## Motivation

## Solution

2020-12-25 07:07 UTC, taiki-e requested changes
Thanks for the PR.

This patch seems to add links that do not work and break existing links as well.
I recommend seeing how these actually look: https://github.com/arniu/tokio/blob/patch-1/tokio/CHANGELOG.md

2020-12-25 07:07 UTC, taiki-e commented on tokio/CHANGELOG.md
> +- sync: spurious wakeup in `watch` ([#3234]).
> ([#3234]).

This (and all other links) is displayed like `[#3234]` in markdown. You have to add links to issues/PRs.

2020-12-25 07:07 UTC, taiki-e commented on tokio/CHANGELOG.md
> -[#2375]: https://github.com/tokio-rs/tokio/pull/2375
Why did you remove these links? This breaks all existing links.

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#3308]: https://github.com/tokio-rs/tokio/pull/3308
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#3093]: https://github.com/tokio-rs/tokio/pull/3093
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#2903]: https://github.com/tokio-rs/tokio/pull/2903
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#2893]: https://github.com/tokio-rs/tokio/pull/2893
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#2092]: https://github.com/tokio-rs/tokio/pull/2092
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#2001]: https://github.com/tokio-rs/tokio/pull/2001
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#1939]: https://github.com/tokio-rs/tokio/pull/1939
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#1874]: https://github.com/tokio-rs/tokio/pull/1874
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#1854]: https://github.com/tokio-rs/tokio/pull/1854
```suggestion
```

2020-12-25 09:16 UTC, taiki-e commented on tokio/CHANGELOG.md
> +[#141]: https://github.com/tokio-rs/tokio/pull/141
```suggestion
```

2020-12-25 09:51 UTC, arniu commented on tokio/CHANGELOG.md
> +[#141]: https://github.com/tokio-rs/tokio/pull/141
I'll run dedup on it.

2020-12-26 21:46 UTC, Darksonn approved these changes
Can you include the 1.0.1 release as well?

2020-12-27 09:39 UTC, Darksonn approved these changes

2020-12-27 14:56 UTC, taiki-e approved these changes

2020-12-27 15:36 UTC, merged