sync: RwLock add try_read and try_write methods
tokio-rs/tokio pull request #3400
Opened 2021-01-10 17:47 UTC by nylonicious

Closes #2284

2021-01-12 06:05 UTC, carllerche requested changes
Thanks for doing this. The implementations look good to me. I left a note about the error types.

2021-01-12 06:05 UTC, carllerche commented on tokio/src/sync/rwlock.rs
> +    pub fn try_read(&self) -> Result<RwLockReadGuard<'_, T>, TryReadError> {
I don't think we need to create new error types for each fn here. We could reuse `TryLockError`. This matches what `std` does.

2021-01-14 18:46 UTC, carllerche approved these changes
Thanks :+1:

2021-01-14 21:36 UTC, hawkw approved these changes
looks good to me — one small docs nit

2021-01-14 21:36 UTC, hawkw commented on tokio/src/sync/rwlock.rs
> +    /// If the access couldn't be acquired immediately returns [`TryLockError`].
```suggestion
    /// If the access couldn't be acquired immediately, returns [`TryLockError`].
```

2021-01-14 21:36 UTC, hawkw commented on tokio/src/sync/rwlock.rs
> +    /// If the access couldn't be acquired immediately returns [`TryLockError`].
```suggestion
    /// If the access couldn't be acquired immediately, returns [`TryLockError`].
```

2021-01-14 23:05 UTC, merged