Implement `OnceCell::wait`
tokio-rs/tokio pull request #4828
Opened 2022-07-12 17:45 UTC by WilliamVenner

This pull request implements `OnceCell::wait`, closing request #4788

## Motivation

The `once_cell` crate provides a `OnceCell::wait` method, which blocks the current thread until a value has been set in the `OnceCell`, returning a reference to the stored value.

This is useful for situations where multiple tasks/threads need to wait on a value to be initialized before continuing, and that value only needs setting once.

This PR implements a future that resolves when a value has been set in the `OnceCell`, providing an async-runtime-friendly implementation of `once_cell`'s `OnceCell::wait` method.

I had a need for this when writing Discord bots, and I wanted to communicate the bot user ID to other tasks, like so:

```rust
use serenity::{async_trait, model::prelude::*, prelude::*};
use tokio::sync::OnceCell;

struct Handler {
    bot_id: OnceCell<UserId>,
}

#[async_trait]
impl EventHandler for Handler {
    async fn message(&self, ctx: Context, msg: Message) {
        msg.reply(&ctx.http, format!("My bot user ID is {}", self.bot_id.wait().await)).await.expect("Failed to reply to message");
    }

    async fn ready(&self, ctx: Context, ready: serenity::model::gateway::Ready) {
        self.bot_id.set(ready.user.id).expect("Failed to set bot ID");
    }
}
```

## Solution

The PR implements the `Future` trait on `&OnceCell<T>` and exposes a `OnceCell::get()` method to idiomatically construct that future.

The future checks if the cell has been initialized, and resolves with a reference to the stored value, otherwise, the future returns Pending.

2022-07-12 18:41 UTC, Noah-Kennedy requested changes

2022-07-12 18:41 UTC, Noah-Kennedy commented on tokio/src/sync/once_cell.rs
> +            Poll::Pending
If this doesn't immediately return ready, the task will never wake, as the waker is lost.

2022-07-12 18:41 UTC, Noah-Kennedy commented on tokio/src/sync/once_cell.rs
> +    pub fn wait(&self) -> impl Future<Output = &T> {
I really don't like the approach of having a method for this and also having the type become a future. This should return a distinct custom future which is woken when the cell is initialized.

2022-07-12 18:42 UTC, Noah-Kennedy commented
@WilliamVenner this should really be implemented such that we hold an internal list of wakers which we wake on initialization.

2022-07-12 19:19 UTC, Noah-Kennedy commented
@WilliamVenner If you'd like, I can go ahead and implement this. Don't want to step on your toes though if you think you've got this.

2022-07-12 19:53 UTC, WilliamVenner commented
I assume that's what you'd have gone for!

Here's a stub of the specialized implementation I was proposing.

```rs
pub struct BarrierCell<T> {
    state: AtomicU8,
    value: UnsafeCell<MaybeUninit<T>>,
    waiters: Notify,
}
impl<T> BarrierCell<T> {
    pub fn new() -> Self {
        Self {
            state: AtomicU8::new(BarrierCellState::Uninitialized as u8),
            value: UnsafeCell::new(MaybeUninit::uninit()),
            waiters: Notify::new(),
        }
    }

    pub async fn wait(&self) -> &T {
        self.waiters.notified().await;
        unsafe { self.get_unchecked() }
    }

    #[inline]
    unsafe fn get_unchecked(&self) -> &T {
        debug_assert!(self.initialized(), "BarrierCell is not initialized");
        self.value.with(|ptr| (*ptr).assume_init_ref())
    }

    pub fn initialized(&self) -> bool {
        self.state.load(Ordering::Acquire) == BarrierCellState::Initialized as u8
    }

    pub fn set(&self, value: T) -> Result<(), SetError<T>> {
        let state = self
            .state
            .fetch_max(BarrierCellState::Writing as u8, Ordering::SeqCst);

        if state == BarrierCellState::Initialized as u8 {
            Err(SetError::AlreadyInitializedError(value))
        } else if state == BarrierCellState::Writing as u8 {
            Err(SetError::InitializingError(value))
        } else {
            self.value
                .with_mut(|ptr| unsafe { (*ptr).as_mut_ptr().write(value) });

            self.state
                .store(BarrierCellState::Initialized as u8, Ordering::Release);

            self.waiters.notify_waiters();
            Ok(())
        }
    }
}
```

I suppose it's not different or more performant enough to justify a whole new cell type, and I think that would also be confusing, but here it is anyway.

2022-07-12 20:06 UTC, Noah-Kennedy commented
It could probably be implemented in a similar manner to notify under the hood actually.

2022-07-12 20:25 UTC, WilliamVenner commented
> Yeah, thinking on this more, we should just do the same trick with holding a list of wakers which we then wake on initialization.

Potential problem with that - I'm not sure we can do that atomically?

If a thread loads `value_set` and it returns `false`, we then add the current waker to the notify list. But in between that and the load, a thread could write into `value_set`. Is this something `Semaphore` could solve?

2022-07-12 20:37 UTC, Noah-Kennedy commented
Yeah I think that might be better actually.

2022-07-12 20:51 UTC, WilliamVenner commented
ACTUALLY - I think it can be done like this?

```rs
pub async fn wait(&self) -> &T {
    // Try to acquire a permit, so that we don't step on the toes of
    // another thread trying to initialize the value
    match self.semaphore.acquire().await {
        Ok(permit) => {
            debug_assert!(!self.initialized()); // at this point, we should not be initialized

            let notified = self.waiters.notified(); // set up a future that will resolve when the value is initialized

            drop(permit); // release the permit, allowing other tasks to initialize the value

            notified.await; // wait for the value to be initialized

            debug_assert!(self.initialized());

            unsafe { self.get_unchecked() }
        }
        Err(_) => {
            debug_assert!(self.initialized());

            // SAFETY: The semaphore has been closed. This only happens
            // when the OnceCell is fully initialized.
            unsafe { self.get_unchecked() }
        }
    }
}
```

2022-07-12 22:36 UTC, Noah-Kennedy commented
I think we could add some sort of "gate" semaphore which can be opened to mass-notify all waiters, and would flip an atomic flag to cause future attempts at waiting to complete immediately.

2022-07-13 06:52 UTC, Darksonn commented
Not sure what you mean by "gate" semaphore? However, closing the semaphore seems like the ideal signal to use for this.

2022-07-13 13:52 UTC, Noah-Kennedy commented
@Darksonn I've been thinking for a while about having a "gate" primitive which allows waiters to wait for the gate to be opened, and, once opened, future attempts to wait on the gate complete immediately.

2022-07-13 16:12 UTC, Darksonn commented
You can do that by having an empty `Semaphore` that you close upon opening it. The `acquire` calls will return when you close it. Of course, a dedicated primitive could be added as well.

2022-07-13 16:41 UTC, Noah-Kennedy commented
Interesting, never thought about that, thanks for the tip!

2022-07-14 17:44 UTC, WilliamVenner commented
I don't think its necessary to implement that for this method, unless you want to use it for other things in future ;)

It turns out the existing semaphore was sufficient to solve the atomicity problem, as you can drop the permit after adding yourself to the notified list, _then_ await the `Notified` future:

```rs
let notified = self.waiters.notified(); // set up a future that will resolve when the value is initialized

drop(permit); // release the permit, allowing other tasks to initialize the value

notified.await; // wait for the value to be initialized
```

2022-08-10 13:53 UTC, Darksonn commented
I would prefer a PR that implements a way to wait for a `Semaphore` to be closed. It can be followed up by a PR that implements `OnceCell::wait` using it.

2022-11-01 19:13 UTC, carllerche commented
I'm not sure we should add a way to our Semaphore type to wait for close. "Closing" the semaphore is to prevent new waiters and support a path for a clean shutdown. Waiting for a close signal would require another waiter list and probably should be implemented at a higher level (unless there is a good argument that I am missing).

2022-11-02 12:52 UTC, Darksonn commented
Well, it seemed useful enough to me, but I don't mind dropping plans of supporting that for `Semaphore`.

2022-11-02 13:44 UTC, notgull commented
It feels like the semantics of the `OnceCell` should be modified, in that case.

2023-02-19 13:25 UTC, Darksonn commented
After thinking more about this, I've come to a similar conclusion for `OnceCell`. This makes the type larger, and the vast majority of use-cases don't need it. Instead, we should provide an alternate type for this, or provide documentation that explains how it can be done using existing types.

2023-02-19 13:25 UTC, closed without merging