sync: Add `decrease_permits` method to semaphore
tokio-rs/tokio pull request #6331
Opened 2024-02-07 16:26 UTC by mox692

This PR adds a method to the semaphore that reduces the number of permits.

## Motivation

resolve https://github.com/tokio-rs/tokio/issues/5308.
## Solution
Implement `decrease_permits` that reduces the semaphore's permits by a maximum of `n` and returns the number of permits that were actually reduced.

2024-02-07 21:07 UTC, maminrayej requested changes
Since `forget` is already used to reduce the number of available permits, please rename the methods to `forget_permits` to remain consistent with the existing API.

2024-02-08 14:09 UTC, maminrayej commented
Thanks.

2024-02-08 14:10 UTC, merged

2025-02-13 09:18 UTC, Darksonn commented
To forget an exact number of permits, you can acquire that number of permits and then use [`Permit::forget`](https://docs.rs/tokio/latest/tokio/sync/struct.SemaphorePermit.html#method.forget).

If you have a feature request, you should open a new issue.

2025-02-13 09:21 UTC, tisonkun commented
> you can acquire that number of permits and then use [Permit::forget](https://docs.rs/tokio/latest/tokio/sync/struct.SemaphorePermit.html#method.forget).

This would queue a waiter at the end of the wait list, while forget may prefer to queue a waiter in the front.

> If you have a feature request, you should open a new issue.

Fair enough. I'd first check if it's a valid issue :P