task: stabilize `task::Id` related apis
tokio-rs/tokio pull request #6891
Opened 2024-10-08 13:45 UTC by mox692

Follow up https://github.com/tokio-rs/tokio/pull/6793.

2024-10-08 19:49 UTC, nurmohammed840 approved these changes

2024-10-08 20:14 UTC, Darksonn commented on tokio/src/task/join_set.rs
I was wondering about these ... but I guess it's probably fine.

2024-10-08 20:14 UTC, Darksonn approved these changes

2024-10-08 20:42 UTC, nurmohammed840 requested changes
@mox692,  Did you missed out `TaskMeta` ?

https://github.com/tokio-rs/tokio/blob/679d7657dc267a4d6472597c91cdda8792cf9e97/tokio/src/runtime/task_hooks.rs#L20-L23

Additionally, you also should remove the `#[cfg(tokio_unstable)]` from  `TaskMeta` and every place where it is used.

2024-10-11 10:14 UTC, mox692 commented
> Did you missed out TaskMeta ?

Done.
Note that `TaskMeta` itself is currently unstable, so we still need the `tokio_unstable`  when we want to access the `Id` via `TaskMeta`.

2024-10-11 10:38 UTC, merged