[WIP] make tracing a task public so self-tracing is possible
tokio-rs/tokio pull request #6972
Opened 2024-11-13 16:31 UTC by arielb1

There is some desire to make it possible for tasks to trace themselves to discover slow wakeups, something similar to the test I added.

This PR makes some functions public (but unstable) to make that easier.

WIP: actually add docs.

2024-11-13 17:06 UTC, arielb1 commented
cc @pdxcarl

also for seeing how to make this pass CI

2024-11-13 17:07 UTC, arielb1 commented
cc @carllerche 

also for seeing how to make this pass CI without removing the test

2024-11-18 11:49 UTC, arielb1 commented
[PR status: I'm having some people check out this PR to see if it helps them debug some "slow task" problems. After I see the lessons learned I'll make it less WIP]

2024-11-21 01:14 UTC, jlizen commented
Chiming in, @arielb1 asked me to poke at this implementation in a somewhat realistic scenario where it might be useful.

One such case that I've encountered is while operating a service that uses a Redis cluster as a backend for a distributed precision/adaptive throttling, with various multi-step state operations and differing key ordinality. Redis's single threaded event loop and key slot handling makes it prone to bottlenecks if code is poorly optimized. Debugging performance issues can be complex here, since Redis-perspective per-command logs typically don't include time spent while waiting in the event loop queue, metrics tend to be heavily aggregated, and performance issues are difficult to directly trigger without large-scale load testing (and with realistic traffic shapes). An expert might be able to look through source code and infer bottlenecks, but it 

A bit of magic to systematically trace the slower tasks without a ton of manual scaffolding, and without introducing new bottlenecks due to log/metric outputs, would be quite handy. This change would open up that door, and then other libraries could wrap their futures with self-tracing logic.

I threw together a crude simulation where I ran a redis cluster locally, with 10 nodes, key space distributed evenly. I then simulated a big (and fairly hot) key alongside a bunch of normal keys. My wrapper future takes a trace + dumps that trace as well as key name, in case the duration of the total lookup is > 500ms.

Here is my input:
```
use std::{sync::OnceLock, future::Future, pin::Pin, task::{Context, Poll}, time::{Duration, Instant}, iter};

use itertools::Itertools;
use rand::distributions::{Alphanumeric, DistString};
use redis::{cluster::ClusterClient, cluster_async::ClusterConnection, AsyncCommands};
use tokio::{runtime::dump::{Root, Trace}, task::JoinSet};
use tracing::{error, info};
use tracing_subscriber;

static CONNECTION: OnceLock<ClusterConnection> = OnceLock::new();

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init(); 
    let client = ClusterClient::new(vec!["redis://127.0.0.1:6379"]).unwrap();
    let connection = client.get_async_connection().await.unwrap();
    let _ = CONNECTION.set(connection);

    let elements: Vec<(&'static str, &'static str)> = get_good_keys().into_iter().interleave(get_bad_keys().into_iter()).collect();

    let mut set = JoinSet::new();
    for (key, value) in elements.iter() {
        set.spawn(maybe_traced_redis_set(key, value));
    }

    set.join_all().await;
}


async fn maybe_traced_redis_set(key: &'static str, value: &'static str) {
    let mut connection = CONNECTION.get().unwrap().clone();
    let future = connection.set::<&str, &str, String>(key, value);
    let maybe_traced_future = SelfTracingFuture::new(future, key);

    if let Err(e) = maybe_traced_future.await {
        error!("{e}");
    }
}


fn get_good_keys() -> Vec<(&'static str, &'static str)> {
    (0..50).map(|el| {
        let leaked: &'static str = el.to_string().leak();
        (leaked, leaked)
    }).collect()
}

fn get_bad_keys() -> Vec<(&'static str, &'static str)> {
    let big_key: &'static str = Alphanumeric.sample_string(&mut rand::thread_rng(), 20_000_000).leak();

    vec![("big_key", big_key); 10]
}


pin_project_lite::pin_project! { pub struct SelfTracingFuture<F: Future> {
        #[pin]
        f: Root<F>,
        t_last: State,
        identifier: &'static str,
    }
}

enum State {
    NotStarted,
    Running { since: Instant },
    Alerted,
}


impl<F: Future> SelfTracingFuture<F> {
    fn new(f: F, identifier: &'static str) -> Self {
        Self {
            f: Trace::root(f),
            t_last: State::NotStarted,
            identifier
        }
    }
}


impl<F: Future> Future for SelfTracingFuture<F> {
    type Output = F::Output;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<F::Output> {
        let mut this = self.project();
        let now = Instant::now();
        let t_last = match this.t_last {
            State::Running { since } => Some(*since),
            State::NotStarted => {
                *this.t_last = State::Running { since: now };
                None
            }
            State::Alerted => {
                // don't double-alert for the same future
                None
            }
        };
        if t_last.is_some_and(|t_last| now.duration_since(t_last) > Duration::from_millis(500)) {
            let (res, trace) = tokio::runtime::dump::Trace::capture(|| this.f.as_mut().poll(cx));
            *this.t_last = State::Alerted;
            let identifier = this.identifier;
            info!("{identifier} future ran long: {trace}");
 
            
            return res;
        }
        this.f.poll(cx)
    }
}
```

And here is my output:

```
     Running `build/private/cargo-target/debug/test_trace`
2024-11-21T00:47:04.938855Z  INFO test_trace: big_key future ran long: ╼ <core::pin::Pin<P> as core::future::future::Future>::poll at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
  └╼ redis::commands::AsyncCommands::set::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25.4/src/commands/macros.rs:169:69
     └╼ redis::cmd::Cmd::query_async::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25.4/src/cmd.rs:434:48
        └╼ <core::pin::Pin<P> as core::future::future::Future>::poll at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
           └╼ redis::cluster_async::ClusterConnection<C>::route_command::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25.4/src/cluster_async/mod.rs:107:14
              └╼ <tokio::sync::oneshot::Receiver<T> as core::future::future::Future>::poll at /workplace/jlizen/GokuBotsAtpAggregator/src/tokio/tokio/src/sync/oneshot.rs:1112:30
                 └╼ tokio::sync::oneshot::Inner<T>::poll_recv at /workplace/jlizen/GokuBotsAtpAggregator/src/tokio/tokio/src/sync/oneshot.rs:1143:16
2024-11-21T00:47:05.130502Z  INFO test_trace: big_key future ran long: ╼ <core::pin::Pin<P> as core::future::future::Future>::poll at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
  └╼ redis::commands::AsyncCommands::set::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25.4/src/commands/macros.rs:169:69
     └╼ redis::cmd::Cmd::query_async::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25.4/src/cmd.rs:434:48
        └╼ <core::pin::Pin<P> as core::future::future::Future>::poll at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
           └╼ redis::cluster_async::ClusterConnection<C>::route_command::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25.4/src/cluster_async/mod.rs:107:14
              └╼ <tokio::sync::oneshot::Receiver<T> as core::future::future::Future>::poll at /workplace/jlizen/GokuBotsAtpAggregator/src/tokio/tokio/src/sync/oneshot.rs:1112:30
                 └╼ tokio::sync::oneshot::Inner<T>::poll_recv at /workplace/jlizen/GokuBotsAtpAggregator/src/tokio/tokio/src/sync/oneshot.rs:1143:16
2024-11-21T00:47:05.130432Z  INFO test_trace: big_key future ran long: ╼ <core::pin::Pin<P> as core::future::future::Future>::poll at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/future/future.rs:123:9
  └╼ redis::commands::AsyncCommands::set::{{closure}} at /workplace/jlizen/GokuBotsAtpAggregator/src/GokuRustCommons/build/private/cargo-home/registry/src/-6353be53fb99b376/redis-0.25. [...]

2024-11-21 15:45 UTC, jlizen commented
Going to also throw in a test against a more realistic application that has more complicated usage of the tokio runtime to see if anything rattles loose.

2024-12-16 18:56 UTC, jlizen commented
I did some more testing in a real application. It is an axum server that handles user flows across a series of endpoints that span vending javascript to the client, vending inputs for a hashcash proof of work challenge, then various crypto operations to validate the solution and vend an encrypted token.

I injected the self-tracing task functionality in an outer tower middleware layer. It dumps a trace in case a request processes longer for 500ms. I then injected a 5% chance of a sleep inside a place where we make a remote call to AWS DynamoDB. This mimics a real performance bottleneck we encountered, due to overlarge table size, that was annoying to debug due to lack of specific metrics wrapping that remote call at the time.

I then simulated user realistic user flows that hit all endpoints in the browser, acquired tokens, etc. I didn't test at load but did send enough traffic to hit a bit of concurrency. I didn't see any signs of strange behavior with regard to the executor or otherwise. Seemed to behave as expected.

The stack trace was useful and pointed directly to the line of code that had the sleep added. See abbreviated output below:
```
warn 2024-12-16T18:45:51.813062959Z long running task: ╼ 
<snip> 
 └╼ test_app[5d607e4097ef04f4]::routing::apis::<test_app_backends[6d9dd0500a3162d0]::cp_datastore::backends::api_gateway_proxy::ApiGatewayProxy>::{closure#4} at /TestApp/test_app/src/routing.rs:269:22
    └╼ test_app[5d607e4097ef04f4]::handlers::verify::verify_handler::<test_app_backends[6d9dd0500a3162d0]::cp_datastore::backends::api_gateway_proxy::ApiGatewayProxy> at /TestApp/test_app/src/handlers/verify.rs:305:1
       └╼ test_app[5d607e4097ef04f4]::handlers::verify::verify_handler::<test_app_backends[6d9dd0500a3162d0]::cp_datastore::backends::api_gateway_proxy::ApiGatewayProxy>::{closure#0} at /TestApp/test_app/src/handlers/verify.rs:365:6
          └╼ test_app[5d607e4097ef04f4]::handlers::verify::verify_handler_inner::<test_app_backends[6d9dd0500a3162d0]::cp_datastore::backends::api_gateway_proxy::ApiGatewayProxy> at /TestApp/test_app/src/handlers/verify.rs:652:85
             └╼ test_app[5d607e4097ef04f4]::handlers::verify::check_and_insert_with_maybe_sleep at /TestApp/test_app/src/handlers/verify.rs:727:67
                └╼ <tokio[b5f4bbd0e64ee820]::time::sleep::Sleep as core[23aac720c248f827]::future::future::Future> at /TestApp/src/tokio/tokio/src/time/sleep.rs:448:22
                   └╼ <tokio[b5f4bbd0e64ee820]::time::sleep::Sleep> at /TestApp/src/tokio/tokio/src/time/sleep.rs:404:16
```

2025-01-09 15:50 UTC, arielb1 commented
Now ready for review.

2025-01-09 16:07 UTC, Darksonn reviewed
Looks reasonable enough.

2025-01-09 16:07 UTC, Darksonn commented on tokio/src/runtime/dump.rs
> +    /// assert!(!trace.unwrap().resolve_backtraces().is_empty());
This example isn't so nice. I would probably do something along these lines:
```rs
// some future
let mut test_future = std::pin!(async move { tokio::task::yield_now().await; 0 });

// trace it once
let (trace, res) = Trace::root(std::future::poll_fn(|cx| {
    let (res, trace) = Trace::capture(|| test_future.as_mut().poll(cx));
    Poll::Ready((trace, res))
})).await;

let output = match res {
    Poll::Ready(output) => output,
    Poll::Pending => test_future.await,
};

println!("{trace}");
```
Perhaps we should have a function along these lines to make it easier?

2025-01-09 16:07 UTC, Darksonn commented on tokio/tests/task_trace_self.rs
> +}
The formatting here could be improved.

2025-01-09 16:07 UTC, Darksonn commented on tokio/tests/task_trace_self.rs
> +};
We don't use this syntax for imports. Generally, we have one `use std::` per module.

2025-01-09 16:14 UTC, arielb1 commented on tokio/src/runtime/dump.rs
> +    /// assert!(!trace.unwrap().resolve_backtraces().is_empty());
Will switch to your example. My intended use is closer to the `task_trace_self` test. I think a helper function would better fit in a separate PR.

2025-01-10 08:36 UTC, Darksonn commented
Seems like the doc-tests fail to compile.

2025-01-10 23:39 UTC, arielb1 commented
fixed doctests

2025-01-13 17:01 UTC, jswrenn requested changes
A few nits, but this mostly LGTM.

2025-01-13 18:42 UTC, arielb1 commented on tokio/src/runtime/dump.rs
> +    pub fn root<F>(f: F) -> Root<F>
What do similar functions do in Tokio?

2025-01-13 18:45 UTC, arielb1 commented on tokio/src/runtime/dump.rs
> +    /// Runs the function `f` in tracing mode, and returns its result along with the resulting [`Trace`].
it seems to me obvious enough why would you use it - if you want to see what a **single** future is doing

2025-01-13 19:40 UTC, jswrenn reviewed
LGTM

2025-01-14 10:23 UTC, arielb1 commented
Waiting for you @Noah-Kennedy

2025-01-14 13:45 UTC, Darksonn commented on tokio/src/runtime/dump.rs
> +    pub fn root<F>(f: F) -> Root<F>
We don't use it so much, but I think `impl Trait` was not available when we released Tokio 1.0.0. The `*Ext` traits use private types for the return types to simulate it, though.

Anyway, I think an explicit type is fine here.

2025-01-14 13:46 UTC, Darksonn commented on tokio/src/runtime/dump.rs
> +    /// that will be captured in the returning [`Trace`].
Yeah, it can also happen due to e.g. coop.

2025-01-14 15:17 UTC, Darksonn commented on tokio/src/runtime/dump.rs
> +    /// that will be captured in the returning [`Trace`].
Ah, no, I did not notice that you had already removed it. Go ahead and mark such conversations resolved.

2025-01-27 21:01 UTC, carllerche approved these changes

2025-01-27 21:09 UTC, merged